### PR TITLE
Teddit and LibReddit are dead, should be replaced by Redlib

### PR DESCRIPTION
**Pull request by I-I-IT**
See [Redlib github](https://github.com/redlib-org/redlib).
I choose redlib.privacy.com.de cause it has good reliability.
redlib-instances

I also changed redirect to xcancel.com, but didn't change other files.

### CODE REVIEW

**Comment by unixfox** [comment]
Sorry not interested. One change to anything he wants using the preferences.

**Comment by I-I-IT** [comment]
> Sorry not interested. One change to anything he wants using the preferences.

 Why keep redirecting to a service that is dead ? This is bad UX and potentially a security risk (if domain get bought in the future).

It's not like this would take a lot of time or effort.

**Comment by unixfox** [comment]
This github repo hosts the code of xcancel.com. xcancel.com redirection for reddit.com is to old.reddit.com because I like the old reddit interface.

If you don't like to have old.reddit.com, you are free to change it in the preferences.

**Comment by I-I-IT** [comment]
>This github repo hosts the code of xcancel.com. xcancel.com redirection for reddit.com is to old.reddit.com because I like the old reddit interface.

I see.

**Pull request closed without merging**
